services:
  mysql:
    image: mysql:8
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: moustass
      MYSQL_USER: ''
      MYSQL_PASSWORD: ''
      MYSQL_ALLOW_EMPTY_PASSWORD : yes
    ports:
      - "3306:3306"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

    networks:
      - backend-net

  backend:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: backend-container
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: ''
      DB_NAME: moustass
    networks:
      - backend-net

  frontend:
    image: httpd:2.4
    container_name: frontend-container
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./frontend:/usr/local/apache2/htdocs
      - ./apache.conf:/usr/local/apache2/conf/httpd.conf
      - ./ssl.conf:/usr/local/apache2/conf/ssl.conf
      - ./ssl/server.crt:/usr/local/apache2/conf/server.crt
      - ./ssl/server.key:/usr/local/apache2/conf/server.key
      - ./frontend/logs:/usr/local/apache2/logs
      - ./frontend/cache:/usr/local/apache2/cache
    depends_on:
      - backend
    networks:
      - backend-net

  

networks:
  backend-net:
