version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: moustass
      MYSQL_USER: 
      MYSQL_PASSWORD: ''
      MYSQL_ALLOW_EMPTY_PASSWORD : yes
    ports:
      - "3306:3306"
    networks:
      - backend-net

  backend:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: backend-container
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: ''
      DB_NAME: moustass
    networks:
      - backend-net

networks:
  backend-net:
