name: CI/CD Pipeline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Cache node modules
      uses: actions/cache@v3
      with:
        path: |
          **/node_modules
        key: ${{ runner.os }}-modules-${{ hashFiles('**/package.json') }}
        restore-keys: |
          ${{ runner.os }}-modules-

    - name: Install Backend Dependencies
      run: |
        cd backend
        npm install

    - name: Run Backend Tests
      run: |
        cd backend
        npm test -- --passWithNoTests || true

    - name: Build Application
      run: |
        cd backend
        npm run build || echo "No build script found"

    - name: Deploy to Production
      if: github.event_name == 'push' && github.ref == 'refs/heads/master'
      run: |
        echo "Add your deployment commands here"
        # Example deployment commands:
        # - For Heroku: git push heroku master
        # - For Vercel: vercel --prod
        # - For a VPS: rsync -avz --exclude 'node_modules' ./ user@your-server:/path/to/app/ 
